theme: jekyll-theme-hacker
title: Jerry's Blog
description: Recording what I learned everyday
author: Jerry Zhang
github: [metadata]
paginate: 10
paginate_path: "/_posts/page:num/"
timezone: America/Toronto
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
google_analytics: UA-134525874-1

#baseurl: "/Github-blog"

# Sidebar settings
#sidebar: true  #添加侧边栏
#sidebar-about-description: "简单的描述一下你自己"
#sidebar-avatar: /img/avatar-by.jpg
