theme: jekyll-theme-hacker
title: Jerry4013's Blog
description: Recording what I learned everyday
author:
  name: Jingchao Zhang
  email: jingchao.zhang@mail.concordia.ca
  url: https://jerry4013.github.io/Github-blog/