theme: jekyll-theme-hacker
title: Jerry's Blog
description: Recording what I learned everyday
author: Jerry Zhang
github: [metadata]
  repository_url: "https://github.com/Jerry4013/Github-blog.git"
timezone: America/Toronto
plugins:
  - jekyll-redirect-from
#baseurl: "/Github-blog"

# Sidebar settings
#sidebar: true  #添加侧边栏
#sidebar-about-description: "简单的描述一下你自己"
#sidebar-avatar: /img/avatar-by.jpg
