theme: jekyll-theme-hacker
title: Jerry's Blog
description: Recording what I learned everyday
author: Jerry Zhang
github: [metadata]
timezone: America/Toronto
plugins:
  - jekyll-redirect-from
#baseurl: "/Github-blog"
